name: tweet_app
description: "Tweet app built using flutter for UI, Typescript for backend, and mongoDB for databases."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0-24.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  dio: ^5.4.1
  onboarding: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/tweetz.png
    - assets/images/sky.jpg
    - assets/images/person.jpg
    - assets/images/leaf.jpg
