// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCgPPMgLDv0p5O7Z7jTW7nWiJmufRBN2s',
    appId: '1:651544717148:web:22ad7efd86c922f9984399',
    messagingSenderId: '651544717148',
    projectId: 'tweetz-e4ab3',
    authDomain: 'tweetz-e4ab3.firebaseapp.com',
    storageBucket: 'tweetz-e4ab3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASrys1WO2SU7nbo3wowlUNykK0Xwg0cDU',
    appId: '1:651544717148:android:89e56eb29bec393b984399',
    messagingSenderId: '651544717148',
    projectId: 'tweetz-e4ab3',
    storageBucket: 'tweetz-e4ab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN5rWu2xWxSnc49OuQxKSTPwu_F2riQ58',
    appId: '1:651544717148:ios:c9d9988e7939bed9984399',
    messagingSenderId: '651544717148',
    projectId: 'tweetz-e4ab3',
    storageBucket: 'tweetz-e4ab3.appspot.com',
    iosBundleId: 'com.example.tweetApp',
  );
}
